# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Queen Yekels Unrivaled workflow
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Update npm pm2 path & Stop queenyekelunrivaled pm2 service
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.SSH_HOST}} # Ip address of the server
          key: ${{secrets.SSH_PRIVATE_KEY}} # private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # user of the server
          script: |
            # Update path to include npm pm2
            export NVM_DIR=$HOME/.nvm
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

            # stop application
            pm2 delete -s queenyekelsunrivaled || :

      - name: checkout
        uses: actions/checkout@v1

      - name: Update project repo using git commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.SSH_HOST}} # Ip address of the server
          key: ${{secrets.SSH_PRIVATE_KEY}} # private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # user of the server
          script: |
            # Install application updates
            cd ~/queenyekelsunrivaled
            git fetch
            git reset --hard origin/main
            # Migrate Database
            prisma migrate deploy

            # Setup frontend
            npm install
            npm rebuild node-sass
            npm audit fix

            # Setup server
            cd server
            npm install
            npm audit fix

            # cd back to project root
            cd ~/queenyekelsunrivaled

      - name: Start queenyekelunrivaled pm2 service
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # Ip address of the server
          key: ${{secrets.SSH_PRIVATE_KEY}} # private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # user of the server
          script: |
            # start application
            cd ~/queenyekelsunrivaled
            ls
            echo pwd
            # node run.js
