# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Stop all pm2 service
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # Ip address of the server
          key: ${{secrets.SSH_PRIVATE_KEY}} # private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # user of the server
          script: npx pm2 stop all
            
      - name: checkout
        uses: actions/checkout@v1
        
      - name: copy file via ssh key
        uses: ./
        with:
          host: ${{secrets.SSH_HOST}} # Ip address of the server
          key: ${{secrets.SSH_PRIVATE_KEY}} # private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # user of the server
          source: "."
          target: "queenyekelsunrivaled"
            
      - name: Start node
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # Ip address of the server
          key: ${{secrets.SSH_PRIVATE_KEY}} # private or public key of the server
          username: ${{secrets.SSH_USERNAME}} # user of the server
          script: npx pm2 start "npm start"
          
    
